// ECMDroid iOS - Diagnostic Tool for Buell Motorcycles
// Copyright (C) 2012 by Michel Marti
// iOS port Copyright (C) 2025
// Licensed under GPL-3.0
//
// Torque specifications for Buell XB models. Data ported verbatim from the
// original ECMDroid Android resource (res/xml/torque_values.xml). These are
// reference values only — always confirm against the factory service manual.

import Foundation

struct TorqueSpec: Identifiable {
    let id = UUID()
    let fastener: String
    let spec: String
}

struct TorqueCategory: Identifiable {
    let id = UUID()
    let name: String
    let specs: [TorqueSpec]
}

enum TorqueData {
    static let modelName = "Buell XB models"

    static let categories: [TorqueCategory] = [
        TorqueCategory(name: "Chasis", specs: [
            TorqueSpec(fastener: "Airbox cover fasteners", spec: "1-4 Nm"),
            TorqueSpec(fastener: "Airhorn fastener", spec: "8-10 Nm"),
            TorqueSpec(fastener: "Axle pinch fastener, rear", spec: "40 Nm (Anti-Seize)"),
            TorqueSpec(fastener: "Axle rear", spec: "31-36 Nm, open 2 turns, retighten to 65-70 Nm (Anti-Seize)"),
            TorqueSpec(fastener: "Axle pinch fastener, front", spec: "27-30 Nm"),
            TorqueSpec(fastener: "Axle front", spec: "53-56 Nm (Anti-Seize, compress suspension 'before' tighten)"),
            TorqueSpec(fastener: "Bank angle sensor", spec: "1-4 Nm"),
            TorqueSpec(fastener: "Belt guard, upper", spec: "1-4 Nm"),
            TorqueSpec(fastener: "Belt guard, lower", spec: "1-4 Nm"),
            TorqueSpec(fastener: "Brake hand lever housing fastener", spec: "9-10 Nm"),
            TorqueSpec(fastener: "Brake lamp switch fastener, front", spec: "0,8-1 Nm"),
            TorqueSpec(fastener: "Brake line p-clamp fastener, front", spec: "4-7 Nm"),
            TorqueSpec(fastener: "Brake line p-clamp fastener, rear", spec: "4-7 Nm"),
            TorqueSpec(fastener: "Break pedal fastener", spec: "30-33 Nm (Loctite 272)"),
            TorqueSpec(fastener: "Brake pin hanger set, front", spec: "15-19 Nm"),
            TorqueSpec(fastener: "Brake pin hanger set, rear", spec: "15-19 Nm"),
            TorqueSpec(fastener: "Brake pin plug, rear", spec: "2-3 Nm"),
            TorqueSpec(fastener: "Brake reservoir fastener, rear", spec: "11-14 Nm"),
            TorqueSpec(fastener: "Caliper banjo bolt, front", spec: "22-27 Nm (metric)"),
            TorqueSpec(fastener: "Caliper banjo bolt, rear", spec: "22-27 Nm (metric)"),
            TorqueSpec(fastener: "Caliper bleeder valves", spec: "7 Nm"),
            TorqueSpec(fastener: "Caliper carrier, rear", spec: "32-35 Nm"),
            TorqueSpec(fastener: "Caliper fasteners, front", spec: "20-26 Nm"),
            TorqueSpec(fastener: "Caliper mounting fasteners, front", spec: "47-50 Nm"),
            TorqueSpec(fastener: "Caliper mounting large fastener, rear", spec: "24-28 Nm"),
            TorqueSpec(fastener: "Caliper mounting small fastener, rear", spec: "19-24 Nm"),
            TorqueSpec(fastener: "Chin fairing fastener", spec: "4-5 Nm"),
            TorqueSpec(fastener: "Clamp Fasteners Handlebar", spec: "14-16 Nm (S model)"),
            TorqueSpec(fastener: "Clutch cable p-clamp", spec: "1-4 Nm"),
            TorqueSpec(fastener: "Clutch lever clamp pinch fastener", spec: "4-7 Nm"),
            TorqueSpec(fastener: "Clutch lever pivot fastener", spec: "4-5 Nm"),
            TorqueSpec(fastener: "Electronic control module fastener", spec: "8-11 Nm (R model)"),
            TorqueSpec(fastener: "Engine shroud air scoop", spec: "1-4 Nm"),
            TorqueSpec(fastener: "Exhaust header mounting nut", spec: "8-11 Nm"),
            TorqueSpec(fastener: "Fairing support bracket fastener", spec: "22-26 Nm (R model)"),
            TorqueSpec(fastener: "Flasher fastener", spec: "3-5 Nm"),
            TorqueSpec(fastener: "Footpeg mount fastener, rider", spec: "12-15 Nm"),
            TorqueSpec(fastener: "Footpeg mount, passenger", spec: "34-38 Nm"),
            TorqueSpec(fastener: "Fork cap", spec: "30-40 Nm"),
            TorqueSpec(fastener: "Fork center bolt", spec: "30-40 Nm"),
            TorqueSpec(fastener: "Fork clamp lower", spec: "18-20 Nm (Loctite 272)"),
            TorqueSpec(fastener: "Fork clamp upper", spec: "23-26 Nm (Loctite 272)"),
            TorqueSpec(fastener: "Fork damper locknut", spec: "30-40 Nm"),
            TorqueSpec(fastener: "Front fender fastener", spec: "1-4 Nm"),
            TorqueSpec(fastener: "Front isolator bolt", spec: "66-69 Nm"),
            TorqueSpec(fastener: "Front isolator bracket mouting fastener", spec: "66-69 Nm"),
            TorqueSpec(fastener: "Front isolator snubber, upper", spec: "1-4 Nm"),
            TorqueSpec(fastener: "Front isolator threaded frame insert", spec: "66-69 Nm"),
            TorqueSpec(fastener: "Fuse block and relay fasteners", spec: "1-4 Nm (R model)"),
            TorqueSpec(fastener: "Hand lever pivot fastener", spec: "9-14 Nm"),
            TorqueSpec(fastener: "Handlebar clipon fastener, left", spec: "33-35 Nm (Loctite 272, R model)"),
            TorqueSpec(fastener: "Handlebar clipon fastener, right", spec: "33-35 Nm (Loctite 272, R model)"),
            TorqueSpec(fastener: "Headlight fasteners", spec: "2,3-2,8 Nm (R model)"),
            TorqueSpec(fastener: "Headlight support bracket pivot fasteners", spec: "8-11 Nm (R model)"),
            TorqueSpec(fastener: "Heel guard fasteners, passenger", spec: "5-8 Nm"),
            TorqueSpec(fastener: "Heel guard fasteners, rider", spec: "8-11 Nm"),
            TorqueSpec(fastener: "Idler pulley assembly", spec: "44-47 Nm"),
            TorqueSpec(fastener: "Instrument cluster fastener", spec: "4-5 Nm"),
            TorqueSpec(fastener: "License plate fastener", spec: "4-5 Nm"),
            TorqueSpec(fastener: "Main battery ground fastener", spec: "8-11 Nm (R model)"),
            TorqueSpec(fastener: "Master cylinder banjo bolt, front", spec: "22-27 Nm (metric)"),
            TorqueSpec(fastener: "Master cylinder banjo bolt, rear", spec: "22-27 Nm (metric)"),
            TorqueSpec(fastener: "Master cylinder cover fastener, front", spec: "1-1,5 Nm"),
            TorqueSpec(fastener: "Master cylinder mounting fasteners,rear", spec: "8-11 Nm"),
            TorqueSpec(fastener: "Mirror fasteners", spec: "7-8 Nm (R model)"),
            TorqueSpec(fastener: "Muffler mounting block fastener, front", spec: "30-34 Nm"),
            TorqueSpec(fastener: "Muffler mounting block fastener, rear", spec: "43-49 Nm"),
            TorqueSpec(fastener: "Muffler strap fastener, front", spec: "12-14 Nm"),
            TorqueSpec(fastener: "Muffler strap fastener, rear", spec: "5-7 Nm"),
            TorqueSpec(fastener: "Oil cooler air scoop", spec: "14-16 Nm"),
            TorqueSpec(fastener: "Oil drain plug", spec: "20 Nm"),
            TorqueSpec(fastener: "Oil line fittings", spec: "39-42 Nm"),
            TorqueSpec(fastener: "Passenger seat latch", spec: "7-11 Nm"),
            TorqueSpec(fastener: "Pivot shaft pinch bolt", spec: "23-26 Nm"),
            TorqueSpec(fastener: "Ram air scoop", spec: "1-4 Nm"),
            TorqueSpec(fastener: "Rear fender fastener", spec: "1-4 Nm"),
            TorqueSpec(fastener: "Rotor mounting fasteners, front", spec: "34-37 Nm (EBR mount kit: 21-25 Nm)"),
            TorqueSpec(fastener: "Rotor mounting fasteners, rear", spec: "34-37 Nm"),
            TorqueSpec(fastener: "Safety interlock fastener", spec: "0,8-1,1 Nm"),
            TorqueSpec(fastener: "Seat fasteners", spec: "1-4 Nm (R model)"),
            TorqueSpec(fastener: "Shock absorber, lower", spec: "23-26 Nm"),
            TorqueSpec(fastener: "Shock mounting fastener, upper", spec: "66-69 Nm"),
            TorqueSpec(fastener: "Shock reservoir clamp, rear", spec: "11-16 Nm (R model)"),
            TorqueSpec(fastener: "Sidestand bracket fasteners", spec: "34-37 Nm"),
            TorqueSpec(fastener: "Sidestand pivot bolt", spec: "24-27 Nm"),
            TorqueSpec(fastener: "Sidestand switch fastener", spec: "4-7 Nm (XB9 Models)"),
            TorqueSpec(fastener: "Sprocket cover fastener", spec: "1-4 Nm"),
            TorqueSpec(fastener: "Sprocket fasteners", spec: "48-50 Nm"),
            TorqueSpec(fastener: "Steering stem cap", spec: "52-57 Nm"),
            TorqueSpec(fastener: "Steering stem pinch fastener", spec: "23-26 Nm"),
            TorqueSpec(fastener: "Swingarm brace mounting fastener", spec: "34-37 Nm"),
            TorqueSpec(fastener: "Swingarm pivot shaft", spec: "32-35 Nm"),
            TorqueSpec(fastener: "Switch housing fasteners", spec: "3-4 Nm"),
            TorqueSpec(fastener: "Tail body work, lower", spec: "4-5 Nm (R model)"),
            TorqueSpec(fastener: "Tail body work, upper", spec: "1-4 Nm (R model)"),
            TorqueSpec(fastener: "Tail frame to frame", spec: "28-31 Nm (R model)"),
            TorqueSpec(fastener: "Tail Section Fasteners Left/Right", spec: "28,5-31,2 Nm (S model)"),
            TorqueSpec(fastener: "Tail Sektion Fasteners Rea", spec: "11,5-12,7 Nm (S model)"),
            TorqueSpec(fastener: "Torca clamp", spec: "54-61 Nm"),
            TorqueSpec(fastener: "Turn signal and reflectors", spec: "2-3 Nm"),
            TorqueSpec(fastener: "Valve stem nut", spec: "4-5 Nm"),
        ]),
        TorqueCategory(name: "Engine", specs: [
            TorqueSpec(fastener: "'V' bracket to main frame", spec: "13,6-16,3 Nm"),
            TorqueSpec(fastener: "All tie bars", spec: "33,9-36,6 Nm"),
            TorqueSpec(fastener: "Anti-rotation screws lifter)", spec: "6-7 Nm"),
            TorqueSpec(fastener: "Crankcase 5/16 in. screws", spec: "20-26 Nm"),
            TorqueSpec(fastener: "Cylinder head screws", spec: "See Notes (Special pattern to tighten, see Service Manual)"),
            TorqueSpec(fastener: "Cylinder studs", spec: "14-27 Nm (Special pattern to tighten, see Service Manual)"),
            TorqueSpec(fastener: "Exhaust header nuts", spec: "8,1-10,8 Nm"),
            TorqueSpec(fastener: "Feed oil line at oil reservoir", spec: "27,1-29,8 Nm"),
            TorqueSpec(fastener: "Feed oil line at pump to cooler", spec: "24,4-27,1 Nm"),
            TorqueSpec(fastener: "Feed oil line at rear to oil pump", spec: "24,4-27,1 Nm"),
            TorqueSpec(fastener: "Feed oil line at the oil cooler", spec: "20,3-23 Nm"),
            TorqueSpec(fastener: "Front isolator bolt", spec: "66-69 Nm"),
            TorqueSpec(fastener: "Front isolator bracket mounting fastener", spec: "66-69 Nm"),
            TorqueSpec(fastener: "Front muffler strap fastener", spec: "12,2-13,6 Nm"),
            TorqueSpec(fastener: "Gearcase cover screws", spec: "9-12 Nm (Special pattern to tighten, see Service Manual)"),
            TorqueSpec(fastener: "Oil cooler feed line at the oil pump", spec: "24,4-27,1 Nm"),
            TorqueSpec(fastener: "Oil cooler return line fitting at crankcase", spec: "20,3-23 Nm"),
            TorqueSpec(fastener: "Oil cooler return line fitting at the oil cooler", spec: "20,3-23 Nm"),
            TorqueSpec(fastener: "Oil cooler return oil line", spec: "20,3-23 Nm"),
            TorqueSpec(fastener: "Oil filter adapter", spec: "11-16 Nm (Loctite 243)"),
            TorqueSpec(fastener: "Oil pressure signal light switch", spec: "6-8 Nm"),
            TorqueSpec(fastener: "Oil pump cover screws", spec: "8-9 Nm (Torx)"),
            TorqueSpec(fastener: "Oil pump mounting screws", spec: "8-9 Nm"),
            TorqueSpec(fastener: "Pinion shaft nut", spec: "26-29 Nm"),
            TorqueSpec(fastener: "Piston jet Torx screws", spec: "2,8-4 Nm (Loctite 222)"),
            TorqueSpec(fastener: "Pushrod cover screws", spec: "3-5 Nm"),
            TorqueSpec(fastener: "Rear isolator assembly fasteners", spec: "33,9-36,6 Nm"),
            TorqueSpec(fastener: "Rear isolator bolt", spec: "66,4-69,1 Nm"),
            TorqueSpec(fastener: "Rear muffler bracket", spec: "43,4-48,8 Nm"),
            TorqueSpec(fastener: "Rear muffler straps", spec: "5,4-6,8 Nm"),
            TorqueSpec(fastener: "Reed valve fasteners", spec: "3,4-4,5 Nm"),
            TorqueSpec(fastener: "Return oil line at oir reservoir", spec: "25,8-28,5 Nm"),
            TorqueSpec(fastener: "Return oil line at top front oil pump", spec: "24,4-27,1 Nm"),
            TorqueSpec(fastener: "Rocker box cover screws", spec: "13,6-17,6 Nm"),
            TorqueSpec(fastener: "Rocker box to head bolts", spec: "15-18 Nm (Small fasteners (2))"),
            TorqueSpec(fastener: "Rocker box to head bolts", spec: "15-18 Nm (Small fasteners (3))"),
            TorqueSpec(fastener: "Rocker box to head bolts", spec: "24-30 Nm (Large fasteners)"),
            TorqueSpec(fastener: "Sprocket cover fastener", spec: "1-4 Nm"),
            TorqueSpec(fastener: "Swingarm pivot shaft pinch bolt", spec: "23-25,8 Nm"),
            TorqueSpec(fastener: "Swingarm pivot shaft", spec: "32,5-35,2 Nm"),
            TorqueSpec(fastener: "Torca clamp", spec: "54,2-61 Nm"),
            TorqueSpec(fastener: "Vent oil line at grearcase cover", spec: "13,6-14,9 Nm"),
            TorqueSpec(fastener: "Vent oil line at oil reservoir", spec: "19-21,7 Nm"),
        ]),
        TorqueCategory(name: "Fuel System", specs: [
            TorqueSpec(fastener: "Airbox baseplate fastener", spec: "9,5-13,6 Nm"),
            TorqueSpec(fastener: "Bank angle sensor mounting fastener", spec: "1,4-4,1 Nm"),
            TorqueSpec(fastener: "Battery terminal hardwar", spec: "7-11 Nm"),
            TorqueSpec(fastener: "Cooling fan fasteners", spec: "1,4-4,1 Nm"),
            TorqueSpec(fastener: "Engine temperature sensor", spec: "14-19 Nm"),
            TorqueSpec(fastener: "Fuel cap retaining ring fasteners", spec: "1,9-7,9 Nm"),
            TorqueSpec(fastener: "Fuel pump drain plug", spec: "9,5-12,2 Nm"),
            TorqueSpec(fastener: "Fuel pump harness fastener", spec: "2-2,5 Nm"),
            TorqueSpec(fastener: "Fuel pump screws", spec: "5,4-5,8 Nm"),
            TorqueSpec(fastener: "Fuel pump wire harness fastener", spec: "2-2,5 Nm"),
            TorqueSpec(fastener: "Fuel rail fasteners", spec: "2,7-3,2 Nm (Loctite 222)"),
            TorqueSpec(fastener: "Fuel supply line banjo filling", spec: "9,5-12,2 Nm"),
            TorqueSpec(fastener: "Fuel tank vent valve fasteners", spec: "4,4-4,6 Nm"),
            TorqueSpec(fastener: "Ignition coil mounting screws", spec: "16,3-19 Nm"),
            TorqueSpec(fastener: "Ignition rotor mounting bolt", spec: "5-6 Nm"),
            TorqueSpec(fastener: "Inner timer cover screws", spec: "1-2 Nm"),
            TorqueSpec(fastener: "Intake flange screws", spec: "8-14 Nm"),
            TorqueSpec(fastener: "Oxygen sensor", spec: "54-61 Nm (Anti-Seize)"),
            TorqueSpec(fastener: "Rear shock absorber reservoir clamp rear", spec: "13,6-16,3 Nm"),
            TorqueSpec(fastener: "Throttle position sensor (TPS)", spec: "1,8-2,3 Nm (Loctite 22)"),
            TorqueSpec(fastener: "Timer plate studs", spec: "2-3 Nm"),
            TorqueSpec(fastener: "Upper tie bar", spec: "33,9-36,6 Nm"),
        ]),
        TorqueCategory(name: "Transmission", specs: [
            TorqueSpec(fastener: "Clutch inspection cover fasteners", spec: "9,5-12,2 Nm"),
            TorqueSpec(fastener: "Clutch mainshaft nut", spec: "94,9-108,5 Nm (Loctite 262, left hand threads)"),
            TorqueSpec(fastener: "Crankcase 5/16 in. fasteners", spec: "20,3-25 Nm (Loctite 262)"),
            TorqueSpec(fastener: "Engine sprocket nut", spec: "325-350 Nm (only valid till 2007)"),
            TorqueSpec(fastener: "Negative battery cable at battery terminal", spec: "6,8-10,9 Nm"),
            TorqueSpec(fastener: "Primary cover bolts", spec: "9,0-12,4 Nm (Follow torque sequence)"),
            TorqueSpec(fastener: "Primary cover magnetic drain plug", spec: "19-20 Nm"),
            TorqueSpec(fastener: "Rear axle pinch fastener", spec: "35-45 Nm"),
            TorqueSpec(fastener: "Rear axle", spec: "31-36 Nm, Retighten to 65-70 Nm (Anti-Seize)"),
            TorqueSpec(fastener: "Retention collar screw", spec: "18-23 Nm"),
            TorqueSpec(fastener: "Shift lever pinch screw", spec: "16,3-19,0 Nm"),
            TorqueSpec(fastener: "Transmission sprocket nut", spec: "60-65 Nm (Loctite 262, left hand threads, special torque turn method)"),
            TorqueSpec(fastener: "Transmission sprocket screws", spec: "10,2-12,4 Nm (Replace after 3 removals)"),
        ]),
        TorqueCategory(name: "Electrical", specs: [
            TorqueSpec(fastener: "Starter battery positive cable nut", spec: "7-10 Nm"),
            TorqueSpec(fastener: "Starter mounting bolt", spec: "18-27 Nm"),
            TorqueSpec(fastener: "Battery (+) to starter fastener", spec: "7-10 Nm"),
            TorqueSpec(fastener: "Battery terminal fastener", spec: "8-11 Nm"),
            TorqueSpec(fastener: "Fork clamp upper", spec: "23-26 Nm (Loctite 272)"),
            TorqueSpec(fastener: "Fuse block mounting fasteners", spec: "8,1-10,8 Nm (R model)"),
            TorqueSpec(fastener: "Handlebar control housing screws (left side)", spec: "3-4 Nm"),
            TorqueSpec(fastener: "Handlebar control housing screws (right side)", spec: "3-4 Nm"),
            TorqueSpec(fastener: "Horn fastener", spec: "8,1-10,8 Nm"),
            TorqueSpec(fastener: "Ignition switch body fastener", spec: "1,4-4 Nm"),
            TorqueSpec(fastener: "Ignition switch fastener", spec: "24,4-27,1 Nm (Loctite 272)"),
            TorqueSpec(fastener: "Instrument module fastener", spec: "1,4-4 Nm"),
            TorqueSpec(fastener: "Main battery ground", spec: "5,4-8,1 Nm (R model)"),
            TorqueSpec(fastener: "Neutral indicator switch", spec: "4-6,8 Nm (Loctite 24)"),
            TorqueSpec(fastener: "Relay block mounting fasteners", spec: "8,1-10,8 Nm (R model)"),
            TorqueSpec(fastener: "Rotor mounting fasteners", spec: "10-12 Nm (Loctite 24)"),
            TorqueSpec(fastener: "Spark Plugs", spec: "15-24 Nm"),
            TorqueSpec(fastener: "Stator TORX mounting screws", spec: "3-4 Nm (T-27 TORX with retaining compound, replace after each removal)"),
            TorqueSpec(fastener: "Steering head wiring clamp", spec: "21,7-24,4 Nm (R model)"),
            TorqueSpec(fastener: "Steering stem cap", spec: "52-57 Nm"),
            TorqueSpec(fastener: "Steering stem pinch fastener", spec: "23-26 Nm (Loctite 272)"),
            TorqueSpec(fastener: "Turn signal fastener (rear)", spec: "2,8-3,2 Nm"),
            TorqueSpec(fastener: "Turn signal fasteners (front)", spec: "2,8-3,2 Nm"),
            TorqueSpec(fastener: "Turn signal flasher fastener", spec: "3,4-4,5 Nm"),
            TorqueSpec(fastener: "Voltage regulator mounting fasteners", spec: "4-6,8 Nm (Use new fasteners)"),
        ]),
    ]
}
